eureka:
  instance:
    hostname: api-gateway
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery-service.apps:8070/eureka/

logging:
  level:
    root: INFO

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    enabled: false
    base-url: http://zipkin.tracing:9411
