eureka:
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: http://discovery-service:8070/eureka/
  instance:
    hostname: car-rental-authentication-service
management:
  endpoint:
    health:
      probes:
        enabled: 'true'
    prometheus:
      enabled: 'true'
  endpoints:
    web:
      exposure:
        include: prometheus
spring:
  data:
    mongodb:
      uri: mongodb://root:example@order-service-order-service-db:27017/order?authSource=admin
  rabbitmq:
    host: rabbitmq.messaging
  sleuth:
    sampler:
      probability: '1.0'
  zipkin:
    base-url: http://zipkin.tracing:9411
