eureka:
  instance:
    hostname: car-service
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery-service.apps:8070/eureka/

car-rental-app:
  admin:
    email: admin
    password: admin123
  jwt-secret: sWDXQcubDCnNsll7DoE6s9H2idu/oQoZQJ0eVoRZCN1uLuWE2SCXd3jPdyu3tIBp

queue:
  car-available: CAR_AVAILABLE_QUEUE
  car-unavailable: CAR_UNAVAILABLE_QUEUE
  currency-convert-request: CURRENCY_CONVERT_REQUEST_QUEUE
  order-create: ORDER_CREATE_QUEUE
  order-status-failure: ORDER_STATUS_FAILURE_QUEUE
  order-status-success: ORDER_STATUS_SUCCESS_QUEUE
  order-update: ORDER_UPDATE_QUEUE
  order-update-status: ORDER_UPDATE_STATUS_QUEUE
spring:
  data:
    mongodb:
      uri: mongodb://root:example@car-service-car-service-db:27017/car?authSource=admin
  rabbitmq:
    host: rabbitmq.messaging
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    enabled: false
    base-url: http://zipkin.tracing:9411
