eureka:
  instance:
    hostname: currency-service
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery-service.apps:8070/eureka/

spring:
  data:
    mongodb:
      uri: mongodb://root:example@currency-service-currency-service-db:27017/order?authSource=admin
  rabbitmq:
    host: rabbitmq.messaging
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    enabled: false
    base-url: http://zipkin.tracing:9411
