eureka:
  instance:
    hostname: discovery-service
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    enabled: false
    base-url: http://zipkin.tracing:9411
