eureka:
  instance:
    hostname: opening-hours-service
  client:
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery-service.car-rental:8070/eureka/

spring:
  data:
    mongodb:
      uri: mongodb://root:example@opening-hours-service-db:27017/openinghours?authSource=admin
  rabbitmq:
    host: rabbitmq.messaging
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    enabled: false
    base-url: http://zipkin.tracing:9411
